local base16 = require("plugins.custom.colorscheme")

-- this file is autogenerated by nixos using home-manager
-- if u wanna use the custom theme then do
-- local palette = { base00 = "#000000", ..... base0F = "#ffffff"}
local generated = dofile(vim.fn.stdpath("cache") .. "/generated.lua")
local palette = generated.palette

base16.setup({
    palette = palette,
})
