local base16 = require("lib.custom.base16")

-- this file is autogenerated by nixos using home-manager
-- if u wanna use the custom theme then do
-- local palette = { base00 = "#000000", ..... base0F = "#ffffff"}
local palette = dofile(vim.fn.stdpath("cache") .. "/palette.lua")

base16.setup({
    palette = palette,
})
