return {
    diagnostics = {
        Error = "E",
        Warn = "W",
        Hint = "H",
        Info = "I",
    },
    kinds = {
        Array = "",
        Boolean = "",
        Class = "",
        Collapsed = "",
        Color = "",
        Constant = "",
        Constructor = "",
        Control = "",
        Copilot = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Folder = "",
        Function = "󰊕",
        Interface = "",
        Key = "",
        Keyword = "",
        Method = "",
        Module = "󱒌",
        Namespace = "󰦮",
        Null = "󰟢",
        Number = "󰎠",
        Object = "",
        Operator = "",
        Package = "",
        Property = "",
        Reference = "",
        Snippet = "",
        String = "",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Unknown = "?",
        Value = "",
        Variable = "",
        Warning = "",
    },
    gh_contrib = {
        block_empty = "",
        circle_empty = "",
        block_full = "",
        circle_full = "",
    },
}
