-- NOTE: keeping the default mappings config below so i can use it as cheatsheet
return {
    "neogit",
    spec = { src = "https://github.com/NeogitOrg/neogit" },
    cmd = "Neogit",
    keys = {
        { "<leader>gg", "<cmd>Neogit<cr>", desc = "Show Neogit UI" },
    },
    after = function()
        require("neogit").setup({
            mappings = {
                commit_editor = {
                    ["q"] = "Close",
                    ["<c-c><c-c>"] = "Submit",
                    ["<c-c><c-k>"] = "Abort",
                    ["<m-p>"] = "PrevMessage",
                    ["<m-n>"] = "NextMessage",
                    ["<m-r>"] = "ResetMessage",
                },
                commit_editor_I = {
                    ["<c-c><c-c>"] = "Submit",
                    ["<c-c><c-k>"] = "Abort",
                },
                rebase_editor = {
                    ["p"] = "Pick",
                    ["r"] = "Reword",
                    ["e"] = "Edit",
                    ["s"] = "Squash",
                    ["f"] = "Fixup",
                    ["x"] = "Execute",
                    ["d"] = "Drop",
                    ["b"] = "Break",
                    ["q"] = "Close",
                    ["<cr>"] = "OpenCommit",
                    ["gk"] = "MoveUp",
                    ["gj"] = "MoveDown",
                    ["<c-c><c-c>"] = "Submit",
                    ["<c-c><c-k>"] = "Abort",
                    ["[c"] = "OpenOrScrollUp",
                    ["]c"] = "OpenOrScrollDown",
                },
                rebase_editor_I = {
                    ["<c-c><c-c>"] = "Submit",
                    ["<c-c><c-k>"] = "Abort",
                },
                finder = {
                    ["<cr>"] = "Select",
                    ["<c-c>"] = "Close",
                    ["<esc>"] = "Close",
                    ["<c-n>"] = "Next",
                    ["<c-p>"] = "Previous",
                    ["<down>"] = "Next",
                    ["<up>"] = "Previous",
                    ["<tab>"] = "InsertCompletion",
                    ["<c-y>"] = "CopySelection",
                    ["<space>"] = "MultiselectToggleNext",
                    ["<s-space>"] = "MultiselectTogglePrevious",
                    ["<c-j>"] = "NOP",
                    ["<ScrollWheelDown>"] = "ScrollWheelDown",
                    ["<ScrollWheelUp>"] = "ScrollWheelUp",
                    ["<ScrollWheelLeft>"] = "NOP",
                    ["<ScrollWheelRight>"] = "NOP",
                    ["<LeftMouse>"] = "MouseClick",
                    ["<2-LeftMouse>"] = "NOP",
                },
                popup = {
                    ["?"] = "HelpPopup",
                    ["A"] = "CherryPickPopup",
                    ["d"] = "DiffPopup",
                    ["M"] = "RemotePopup",
                    ["P"] = "PushPopup",
                    ["X"] = "ResetPopup",
                    ["Z"] = "StashPopup",
                    ["i"] = "IgnorePopup",
                    ["t"] = "TagPopup",
                    ["b"] = "BranchPopup",
                    ["B"] = "BisectPopup",
                    ["w"] = "WorktreePopup",
                    ["c"] = "CommitPopup",
                    ["f"] = "FetchPopup",
                    ["l"] = "LogPopup",
                    ["m"] = "MergePopup",
                    ["p"] = "PullPopup",
                    ["r"] = "RebasePopup",
                    ["v"] = "RevertPopup",
                },
                status = {
                    ["j"] = "MoveDown",
                    ["k"] = "MoveUp",
                    ["o"] = "OpenTree",
                    ["q"] = "Close",
                    ["I"] = "InitRepo",
                    ["1"] = "Depth1",
                    ["2"] = "Depth2",
                    ["3"] = "Depth3",
                    ["4"] = "Depth4",
                    ["Q"] = "Command",
                    ["<tab>"] = "Toggle",
                    ["za"] = "Toggle",
                    ["zo"] = "OpenFold",
                    ["x"] = "Discard",
                    ["s"] = "Stage",
                    ["S"] = "StageUnstaged",
                    ["<c-s>"] = "StageAll",
                    ["u"] = "Unstage",
                    ["K"] = "Untrack",
                    ["U"] = "UnstageStaged",
                    ["y"] = "ShowRefs",
                    ["$"] = "CommandHistory",
                    ["Y"] = "YankSelected",
                    ["gp"] = "GoToParentRepo",
                    ["<c-r>"] = "RefreshBuffer",
                    ["<cr>"] = "GoToFile",
                    ["<s-cr>"] = "PeekFile",
                    ["<c-v>"] = "VSplitOpen",
                    ["<c-x>"] = "SplitOpen",
                    ["<c-t>"] = "TabOpen",
                    ["{"] = "GoToPreviousHunkHeader",
                    ["}"] = "GoToNextHunkHeader",
                    ["[c"] = "OpenOrScrollUp",
                    ["]c"] = "OpenOrScrollDown",
                    ["<c-k>"] = "PeekUp",
                    ["<c-j>"] = "PeekDown",
                    ["<c-n>"] = "NextSection",
                    ["<c-p>"] = "PreviousSection",
                },
            },
            status = {
                show_head_commit_hash = true,
                recent_commit_count = 10,
                HEAD_padding = 10,
                HEAD_folded = false,
                mode_padding = 3,
                mode_text = {
                    M = "modified",
                    N = "new file",
                    A = "added",
                    D = "deleted",
                    C = "copied",
                    U = "updated",
                    R = "renamed",
                    T = "changed",
                    DD = "unmerged",
                    AU = "unmerged",
                    UD = "unmerged",
                    UA = "unmerged",
                    DU = "unmerged",
                    AA = "unmerged",
                    UU = "unmerged",
                    ["?"] = "",
                },
            },
            graph_style = "unicode", -- can be "ascii" or "unicode"
            log_pager = nil,
            process_spinner = true,
            telescope_sorter = function()
                return require("telescope").extensions.fzf.native_fzf_sorter()
            end,
            highlight = {
                italic = true,
                bold = true,
                underline = true,
            },
            commit_order = "topo", -- can be "topo", "date", "author-date" or ""
            notification_icon = "󰊢",
            signs = {
                hunk = { "", "" },
                item = { "", "" },
                section = { "", "" },
            },
            integrations = {
                telescope = nil,
                -- Requires you to have `sindrets/diffview.nvim` installed.
                diffview = nil,
                -- Requires you to have `esmuellert/codediff.nvim` installed.
                codediff = nil,
            },
        })
    end,
}
