-- stylua: ignore start
return {
    setup = function(p, hi)
        hi('ColorColumn',    {fg=nil,      bg=p.base02, attr=nil,            sp=nil})
        hi('ComplMatchIns',  {fg=nil,      bg=nil,      attr=nil,            sp=nil})
        hi('Conceal',        {fg=p.base0D, bg=nil,      attr=nil,            sp=nil})
        hi('CurSearch',      {fg=p.base00, bg=p.base09, attr=nil,            sp=nil})
        hi('Cursor',         {fg=p.base01, bg=p.base05, attr=nil,            sp=nil})
        hi('CursorColumn',   {fg=nil,      bg=p.base01, attr=nil,            sp=nil})
        hi('CursorIM',       {fg=p.base01, bg=p.base05, attr=nil,            sp=nil})
        hi('CursorLine',     {fg=nil,      bg=p.base02, attr='trans',        sp=nil})
        hi('CursorLineFold', {fg=p.base0C, bg=p.base02, attr='trans',        sp=nil})
        hi('CursorLineNr',   {fg=p.base09, bg=p.base02, attr='trans',        sp=nil})
        hi('CursorLineSign', {fg=p.base03, bg=p.base02, attr='trans',        sp=nil})
        -- Differs from base16-vim, but according to general style guide
        hi('DiffAdd',        {fg=p.base0B, bg=nil,      attr=nil,            sp=nil})
        hi('DiffChange',     {fg=p.base0C, bg=nil,      attr=nil,            sp=nil})
        hi('DiffDelete',     {fg=p.base08, bg=nil,      attr=nil,            sp=nil})
        hi('DiffText',       {fg=p.base0D, bg=nil,      attr=nil,            sp=nil})
        hi('DiffTextAdd',    {link='DiffAdd'})
        hi('Directory',      {fg=p.base0D, bg=nil,      attr='bold',         sp=nil})
        hi('EndOfBuffer',    {fg=p.base03, bg=nil,      attr=nil,            sp=nil})
        hi('ErrorMsg',       {fg=p.base08, bg=nil,      attr='bold',         sp=nil})
        hi('FloatBorder',    {fg=p.base0F, bg=nil,      attr=nil,            sp=nil})
        hi('FoldColumn',     {fg=p.base0C, bg=nil,      attr=nil,            sp=nil})
        hi('Folded',         {fg=p.base03, bg=nil,      attr=nil,            sp=nil})
        hi('IncSearch',      {fg=p.base00, bg=p.base09, attr=nil,            sp=nil})
        hi('lCursor',        {fg=p.base01, bg=p.base05, attr=nil,            sp=nil})
        hi('LineNr',         {fg=p.base03, bg=p.base01, attr=nil,            sp=nil})
        hi('LineNrAbove',    {fg=p.base03, bg=p.base01, attr=nil,            sp=nil})
        hi('LineNrBelow',    {fg=p.base03, bg=p.base01, attr=nil,            sp=nil})
        -- Slight difference from base16, where `bg=base03` is used. This makes
        -- it possible to comfortably see this highlighting in comments.
        hi('MatchParen',     {fg=nil,      bg=p.base02, attr=nil,            sp=nil})
        hi('ModeMsg',        {fg=p.base0B, bg=nil,      attr=nil,            sp=nil})
        hi('MoreMsg',        {fg=p.base0B, bg=nil,      attr=nil,            sp=nil})
        hi('MsgArea',        {fg=p.base05, bg=p.base00, attr=nil,            sp=nil})
        hi('MsgSeparator',   {fg=p.base02, bg=p.base02, attr=nil,            sp=nil})
        hi('NonText',        {fg=p.base03, bg=nil,      attr=nil,            sp=nil})
        hi('Normal',         {fg=p.base05, bg=p.base01, attr=nil,            sp=nil})
        hi('NormalFloat',    {fg=p.base05, bg=p.base01, attr=nil,            sp=nil})
        hi('NormalNC',       {fg=p.base05, bg=p.base01, attr=nil,            sp=nil})
        hi('OkMsg',          {fg=p.base0B, bg=nil,      attr=nil,            sp=nil})
        hi('Pmenu',          {fg=p.base05, bg=p.base00, attr=nil,            sp=nil})
        hi('PmenuExtra',     {link='Pmenu'})
        hi('PmenuExtraSel',  {link='PmenuSel'})
        hi('PmenuKind',      {link='Pmenu'})
        hi('PmenuKindSel',   {link='PmenuSel'})
        hi('PmenuMatch',     {fg=p.base05, bg=nil,      attr='bold',         sp=nil})
        hi('PmenuMatchSel',  {fg=p.base05, bg=nil,      attr='bold,reverse', sp=nil})
        hi('PmenuSbar',      {fg=nil,      bg=p.base02, attr=nil,            sp=nil})
        hi('PmenuSel',       {fg=p.base05, bg=p.base00, attr='reverse',      sp=nil})
        hi('PmenuThumb',     {fg=nil,      bg=p.base07, attr=nil,            sp=nil})
        hi('Question',       {fg=p.base0D, bg=nil,      attr=nil,            sp=nil})
        hi('QuickFixLine',   {link='CursorLine'})
        hi('Search',         {fg=p.base00, bg=p.base0A, attr=nil,            sp=nil})
        hi('SignColumn',     {fg=p.base09, bg=nil,      attr=nil,            sp=nil})
        hi('SpecialKey',     {fg=p.base03, bg=nil,      attr=nil,            sp=nil})
        hi('SpellBad',       {fg=nil,      bg=nil,      attr='undercurl',    sp=p.base08})
        hi('SpellCap',       {fg=nil,      bg=nil,      attr='undercurl',    sp=p.base0D})
        hi('SpellLocal',     {fg=nil,      bg=nil,      attr='undercurl',    sp=p.base0C})
        hi('SpellRare',      {fg=nil,      bg=nil,      attr='undercurl',    sp=p.base0E})
        hi('StatusLine',     {fg=p.base01, bg=p.base01, attr=nil,            sp=nil})
        hi('StatusLineNC',   {fg=p.base01, bg=p.base01, attr=nil,            sp=nil})
        hi('StderrMsg',      {link='ErrorMsg'})
        hi('StdoutMsg',      {link='MsgArea'})
        hi('Substitute',     {fg=p.base00, bg=p.base0A, attr=nil,            sp=nil})
        hi('TabLine',        {fg=p.base03, bg=p.base00, attr=nil,            sp=nil})
        hi('TabLineFill',    {fg=p.base03, bg=p.base00, attr=nil,            sp=nil})
        hi('TabLineSel',     {fg=p.base0B, bg=p.base00, attr='bold',         sp=nil})
        hi('TermCursor',     {fg=nil,      bg=nil,      attr='reverse',      sp=nil})
        hi('TermCursorNC',   {fg=nil,      bg=nil,      attr='reverse',      sp=nil})
        hi('Title',          {fg=p.base0D, bg=nil,      attr='bold',         sp=nil})
        hi('VertSplit',      {fg=p.base02, bg=p.base02, attr=nil,            sp=nil})
        hi('Visual',         {fg=nil,      bg=p.base02, attr=nil,            sp=nil})
        hi('VisualNOS',      {fg=p.base08, bg=nil,      attr=nil,            sp=nil})
        hi('WarningMsg',     {fg=p.base0A, bg=nil,      attr='bold',         sp=nil})
        hi('Whitespace',     {fg=p.base03, bg=nil,      attr=nil,            sp=nil})
        hi('WildMenu',       {fg=p.base08, bg=p.base0A, attr=nil,            sp=nil})
        hi('WinBar',         {fg=p.base04, bg=p.base02, attr=nil,            sp=nil})
        hi('WinBarNC',       {fg=p.base03, bg=p.base00, attr=nil,            sp=nil})
        hi('WinSeparator',   {fg=p.base03, bg=p.base01, attr=nil,            sp=nil})

        -- Other from 'base16-vim'
        hi('Bold',       {fg=nil,      bg=nil, attr='bold',      sp=nil})
        hi('Italic',     {fg=nil,      bg=nil, attr='italic',    sp=nil})
        hi('TooLong',    {fg=p.base08, bg=nil, attr=nil,         sp=nil})
        hi('Underlined', {fg=nil,      bg=nil, attr='underline', sp=nil})

        -- Patch diff
        hi('diffAdded',   {fg=p.base0B, bg=nil, attr=nil, sp=nil})
        hi('diffChanged', {fg=p.base0C, bg=nil, attr=nil, sp=nil})
        hi('diffFile',    {fg=p.base09, bg=nil, attr=nil, sp=nil})
        hi('diffLine',    {fg=p.base0F, bg=nil, attr=nil, sp=nil})
        hi('diffRemoved', {fg=p.base08, bg=nil, attr=nil, sp=nil})
        hi('Added',       {fg=p.base0B, bg=nil, attr=nil, sp=nil})
        hi('Changed',     {fg=p.base0C, bg=nil, attr=nil, sp=nil})
        hi('Removed',     {fg=p.base08, bg=nil, attr=nil, sp=nil})

        -- Git commit
        hi('gitcommitBranch',        {fg=p.base09, bg=nil, attr='bold', sp=nil})
        hi('gitcommitComment',       {link='Comment'})
        hi('gitcommitDiscarded',     {link='Comment'})
        hi('gitcommitDiscardedFile', {fg=p.base08, bg=nil, attr='bold', sp=nil})
        hi('gitcommitDiscardedType', {fg=p.base0D, bg=nil, attr=nil,    sp=nil})
        hi('gitcommitHeader',        {fg=p.base0E, bg=nil, attr=nil,    sp=nil})
        hi('gitcommitOverflow',      {fg=p.base08, bg=nil, attr=nil,    sp=nil})
        hi('gitcommitSelected',      {link='Comment'})
        hi('gitcommitSelectedFile',  {fg=p.base0B, bg=nil, attr='bold', sp=nil})
        hi('gitcommitSelectedType',  {link='gitcommitDiscardedType'})
        hi('gitcommitSummary',       {fg=p.base0B, bg=nil, attr=nil,    sp=nil})
        hi('gitcommitUnmergedFile',  {link='gitcommitDiscardedFile'})
        hi('gitcommitUnmergedType',  {link='gitcommitDiscardedType'})
        hi('gitcommitUntracked',     {link='Comment'})
        hi('gitcommitUntrackedFile', {fg=p.base0A, bg=nil, attr=nil,    sp=nil})

        -- Built-in diagnostic
        hi('DiagnosticError', {fg=p.base08, bg=nil, attr=nil, sp=nil})
        hi('DiagnosticHint',  {fg=p.base0D, bg=nil, attr=nil, sp=nil})
        hi('DiagnosticInfo',  {fg=p.base0C, bg=nil, attr=nil, sp=nil})
        hi('DiagnosticOk',    {fg=p.base0B, bg=nil, attr=nil, sp=nil})
        hi('DiagnosticWarn',  {fg=p.base0A, bg=nil, attr=nil, sp=nil})

        hi('DiagnosticFloatingError', {fg=p.base08, bg=p.base00, attr=nil, sp=nil})
        hi('DiagnosticFloatingHint',  {fg=p.base0D, bg=p.base00, attr=nil, sp=nil})
        hi('DiagnosticFloatingInfo',  {fg=p.base0C, bg=p.base00, attr=nil, sp=nil})
        hi('DiagnosticFloatingOk',    {fg=p.base0B, bg=p.base00, attr=nil, sp=nil})
        hi('DiagnosticFloatingWarn',  {fg=p.base0A, bg=p.base00, attr=nil, sp=nil})

        hi('DiagnosticSignError', {link='DiagnosticFloatingError'})
        hi('DiagnosticSignHint',  {link='DiagnosticFloatingHint'})
        hi('DiagnosticSignInfo',  {link='DiagnosticFloatingInfo'})
        hi('DiagnosticSignOk',    {link='DiagnosticFloatingOk'})
        hi('DiagnosticSignWarn',  {link='DiagnosticFloatingWarn'})

        hi('DiagnosticUnderlineError', {fg=nil, bg=nil, attr='underline', sp=p.base08})
        hi('DiagnosticUnderlineHint',  {fg=nil, bg=nil, attr='underline', sp=p.base0D})
        hi('DiagnosticUnderlineInfo',  {fg=nil, bg=nil, attr='underline', sp=p.base0C})
        hi('DiagnosticUnderlineOk',    {fg=nil, bg=nil, attr='underline', sp=p.base0B})
        hi('DiagnosticUnderlineWarn',  {fg=nil, bg=nil, attr='underline', sp=p.base0A})

        hi('DiagnosticVirtualTextError', {fg=p.base08, attr='blend', sp=nil})
        hi('DiagnosticVirtualTextHint',  {fg=p.base0D, attr='blend', sp=nil})
        hi('DiagnosticVirtualTextInfo',  {fg=p.base0C, attr='blend', sp=nil})
        hi('DiagnosticVirtualTextOk',    {fg=p.base0B, attr='blend', sp=nil})
        hi('DiagnosticVirtualTextWarn',  {fg=p.base0A, attr='blend', sp=nil})

        -- Built-in LSP
        hi('LspReferenceText',  {fg=nil, bg=p.base02, attr=nil, sp=nil})
        hi('LspReferenceRead',  {link='LspReferenceText'})
        hi('LspReferenceWrite', {link='LspReferenceText'})

        hi('LspSignatureActiveParameter', {link='LspReferenceText'})

        hi('LspCodeLens',          {link='Comment'})
        hi('LspCodeLensSeparator', {link='Comment'})

        -- Built-in snippets
        hi('SnippetTabstop',       {link='Visual'})
        hi('SnippetTabstopActive', {link='SnippetTabstop'})

        -- Built-in markdown syntax
        hi('markdownH1', {fg=p.base09, bg=nil, attr='bold', sp=nil})
        hi('markdownH2', {fg=p.base0A, bg=nil, attr='bold', sp=nil})
        hi('markdownH3', {fg=p.base0B, bg=nil, attr='bold', sp=nil})
        hi('markdownH4', {fg=p.base0C, bg=nil, attr='bold', sp=nil})
        hi('markdownH5', {fg=p.base0D, bg=nil, attr='bold', sp=nil})
        hi('markdownH6', {fg=p.base0F, bg=nil, attr='bold', sp=nil})
    end,
}
-- stylua: ignore end
