-- stylua: ignore start
return {
    setup = function(p, hi)
        -- Standard syntax (affects treesitter)
        hi('Boolean',        {fg=p.base09, bg=nil,      attr=nil,      sp=nil})
        hi('Character',      {fg=p.base09, bg=nil,      attr=nil,      sp=nil})
        hi('Comment',        {fg=p.base04, bg=nil,      attr='italic', sp=nil})
        hi('Conditional',    {fg=p.base0E, bg=nil,      attr=nil,      sp=nil})
        hi('Constant',       {fg=p.base09, bg=nil,      attr=nil,      sp=nil})
        hi('Debug',          {fg=p.base08, bg=nil,      attr=nil,      sp=nil})
        hi('Define',         {fg=p.base0E, bg=nil,      attr=nil,      sp=nil})
        hi('Delimiter',      {fg=p.base0F, bg=nil,      attr=nil,      sp=nil})
        hi('Error',          {fg=p.base08, bg=nil,      attr=nil,      sp=nil})
        hi('Exception',      {fg=p.base08, bg=nil,      attr=nil,      sp=nil})
        hi('Float',          {fg=p.base09, bg=nil,      attr=nil,      sp=nil})
        hi('Function',       {fg=p.base0D, bg=nil,      attr=nil,      sp=nil})
        hi('Identifier',     {fg=p.base08, bg=nil,      attr=nil,      sp=nil})
        hi('Ignore',         {fg=p.base03, bg=nil,      attr=nil,      sp=nil})
        hi('Include',        {fg=p.base0D, bg=nil,      attr=nil,      sp=nil})
        hi('Keyword',        {fg=p.base0E, bg=nil,      attr=nil,      sp=nil})
        hi('Label',          {fg=p.base0C, bg=nil,      attr=nil,      sp=nil})
        hi('Macro',          {fg=p.base08, bg=nil,      attr=nil,      sp=nil})
        hi('Number',         {fg=p.base09, bg=nil,      attr=nil,      sp=nil})
        hi('Operator',       {fg=p.base0C, bg=nil,      attr=nil,      sp=nil})
        hi('PreCondit',      {fg=p.base0E, bg=nil,      attr=nil,      sp=nil})
        hi('PreProc',        {fg=p.base0E, bg=nil,      attr=nil,      sp=nil})
        hi('Repeat',         {fg=p.base0E, bg=nil,      attr=nil,      sp=nil})
        hi('Special',        {fg=p.base0C, bg=nil,      attr=nil,      sp=nil})
        hi('SpecialChar',    {fg=p.base0F, bg=nil,      attr=nil,      sp=nil})
        hi('SpecialComment', {fg=p.base0C, bg=nil,      attr=nil,      sp=nil})
        hi('Statement',      {fg=p.base0D, bg=nil,      attr='bold',   sp=nil})
        hi('StorageClass',   {fg=p.base0A, bg=nil,      attr=nil,      sp=nil})
        hi('String',         {fg=p.base0B, bg=nil,      attr=nil,      sp=nil})
        hi('Structure',      {fg=p.base0C, bg=nil,      attr=nil,      sp=nil})
        hi('Tag',            {fg=p.base0C, bg=nil,      attr=nil,      sp=nil})
        hi('Todo',           {fg=p.base0A, bg=p.base00, attr=nil,      sp=nil})
        hi('Type',           {fg=p.base0A, bg=nil,      attr=nil,      sp=nil})
        hi('Typedef',        {fg=p.base0A, bg=nil,      attr=nil,      sp=nil})
    end,
}
-- stylua: ignore end
